ribbity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tasks.urls"))
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskListView, TaskDetailView

from . import views

urlpatterns = [
    path("home/", views.home, name="home"),
    # path("tasks/", TaskListView.as_view(), name='task-list'),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name='task-detail'),
    # path("tasks/new-task/", views.new_task, name="new-task")
]

tasks/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

status_choices = {
    "ac": "active",
    "c": "completed",
}

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    status = models.CharField(choices=status_choices, blank=True, null=False, default="ac", max_length=2)
    date_created = models.DateTimeField(auto_now=True, blank=True, null=False)
    date_completed = models.DateTimeField(blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    delete_if_deadline_passed = models.BooleanField(blank=True, default=False)
    estimated_duration = models.IntegerField(
        blank=False,
        null=False,
        help_text="An estimate in minutes of the time required to complete this task",
        validators=[
            MinValueValidator(1),
        ]
    )
    description = models.TextField(max_length=1000, blank=True, null=True)
    prerequisites = models.ManyToManyField("self", blank=True, related_name="subsequent_tasks", symmetrical=False)
    priority = models.IntegerField(
        blank=False,
        null=False,
        default=5,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(10)
        ],
        help_text="The priority of this task on a scale from 1 to 10."
    )
    splittable = models.BooleanField(blank=True, null=False, default=False, help_text="Whether or not this task can be split into separate timeblocks.")
    minimum_split_time = models.IntegerField(blank=True, default=15, help_text="The minimum amount of time to spend on this task in a given timeblock")

    def __str__(self):
        return self.name

def has_cycle(stack, seen):
    if len(stack) == 0:
        return True
    current_id = stack[-1]
    current_task = Task.objects.filter(id=current_id)
    prereqs_id_list = current_task.values_list('prerequisites__id', flat=True)
    for prereq in prereqs_id_list:
        if prereq in stack:
            return True
        if prereq in seen:
            continue
        stack.append(prereq)
        if has_cycle(stack, seen):
            return True
        seen.append(prereq)
        stack = stack[:-1]

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name", "estimated_duration", "priority"]

tasks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from datetime import date
from django.views.generic import ListView
from tasks.models import Task
from django.views.generic.detail import DetailView
from .forms import TaskForm
from .models import Task

def todays_day_of_the_week():
    today = date.today().weekday()
    days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    day_of_week_name = days[today]
    return day_of_week_name



def index(request):
    return HttpResponse("Hello, world. You're at the tasks index.")

def home(request):
    context = {"day": todays_day_of_the_week()}
    form = TaskForm(request.POST or None)
    if form.is_valid():
        form.save()
    context['form'] = form
    tasks = Task.objects.all()
    context['tasks'] = tasks
    return render(request, 'home.html', context)

class TaskListView(ListView):
    model = Task
    context_object_name='tasks'

class TaskDetailView(DetailView):
    model = Task

# def new_task(request):
#     context = {}
#     form = TaskForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#     context['form'] = form
#     return render(request, 'home.html', context)

def mark_as_completed(request, id):
    task = get_object_or_404()
    pass

ribbity/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    {% block extra_head %}{% endblock %}
</head>
<body>
<!--    <a href="/home">Home</a>-->
<!--    <a href="/tasks">Tasks</a>-->
    {% block content %}
        <p>Default base content</p>
    {% endblock %}
</body>
</html>


tasks/templates/tasks/home.html
{% extends "base.html" %}

{% block content %}
<p>Happy {{day}}!</p>

<div id="newTaskForm" class="panel">
    <h1>Task form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

</div>
<div id="toDoMaker" class="panel">
    <h1>To do list generator</h1>
    <p>abc</p>
</div>
<div id="allTasks" class="panel">
    <h1>All tasks</h1>
    <ul>
        {% include 'task_list.html' %}
    </ul>
</div>
{% endblock %}

tasks/templates/tasks/new_task.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends "base.html" %}
{% block content %}
<p>Task name: {{ object.name }}</p>
<p>Task description: {{ object.description }}</p>
<p>Task duration: {{ object.estimated_duration }}</p>
{% endblock %}

tasks/templates/tasks/task_list.html
<ul>
    {% for task in tasks %}
        <li><a href="{% url 'task-detail' task.id %}">{{ task.name }}</li>
    {% empty %}
        <li>No tasks found.</li>
    {% endfor %}
</ul>